### ISSUE TITLE
Bus trip controller bug

### ISSUE THREAD

**Issue by guanlongzhao** [csbpku/csce606#2]
There is a bug in the bus trip planning code.

Currently the algorithm finds the nearest stops to the departure and destination location, this is not correct, because the resulting stop may only be available for game day bus routes. For example, if you set the destination as "Evans Library", the code will find "Bonfire" as the nearest stop, which is not available on 11/21/2016.

**Comment by xing-zhao** [comment]
Thanks Guanlong!

**Comment by guanlongzhao** [comment]
Fixed
